# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set work directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.tx ./
RUN pip install --no-cache-dir -r requirements.tx

# Copy application code
COPY . .

# Patch server.py to listen on all interfaces, dynamic port, and root path
RUN sed -i '1iimport os' server.py \
    && sed -i 's/host="127.0.0.1"/host=os.getenv("HOST","0.0.0.0")/' server.py \
    && sed -i 's/port=8000/port=int(os.getenv("PORT",8000))/' server.py \
    && sed -i 's!path="/mcp/"!path="/"!' server.py

# Expose port
EXPOSE 8080

# Default command
CMD ["python", "server.py"]
